import { describe, expect, it } from 'vitest'
import { readFileSync } from 'fs'
import { resolve } from 'path'

const serviceDetailPage = readFileSync(resolve(process.cwd(), 'src/pages/ServiceDetailPage.tsx'), 'utf-8')
const pullBundlePanel = readFileSync(resolve(process.cwd(), 'src/components/PullBundlePanel.tsx'), 'utf-8')
const apiClient = readFileSync(resolve(process.cwd(), 'src/api/client.ts'), 'utf-8')
const types = readFileSync(resolve(process.cwd(), 'src/types/switchboard.ts'), 'utf-8')

describe('freshness visibility contract', () => {
  it('keeps VPN-blocked node inspect results as node action results, not generic API errors', () => {
    expect(apiClient).toContain('connection_status')
    expect(apiClient).toContain('freshness_state')
    expect(apiClient).toContain('last_inspected_at')
    expect(apiClient).toContain('isApiError(res) && !(res as any).node')
    expect(types).toContain('vpn_or_network_blocked')
  })

  it('shows node freshness and sync authority timestamps in service detail', () => {
    expect(serviceDetailPage).toContain('Last inspected')
    expect(serviceDetailPage).toContain('Manager health checked')
    expect(serviceDetailPage).toContain('Manifest last updated')
    expect(serviceDetailPage).toContain('Last synced from node')
    expect(serviceDetailPage).toContain('Saved scope updated')
    expect(serviceDetailPage).toContain('Pull authority updated')
    expect(serviceDetailPage).toContain('Truth source')
    expect(serviceDetailPage).toContain('Data as of')
    expect(serviceDetailPage).toContain('Truth as of')
    expect(serviceDetailPage).toContain('VPN is off or network blocked. Turn VPN on for live verification.')
    expect(serviceDetailPage).toContain('Inspect Node is read-only')
    expect(serviceDetailPage).toContain('Sync From Node imports node state into Control Center')
  })

  it('blocks stale pull-bundle authority with clear operator copy', () => {
    expect(pullBundlePanel).toContain('authority_stale')
    expect(pullBundlePanel).toContain('node_local_scope_timestamp')
    expect(pullBundlePanel).toContain('control_center_scope_timestamp')
    expect(pullBundlePanel).toContain('Stale authority. Run Sync From Node with VPN on.')
    expect(pullBundlePanel).toContain('Manager truth is unavailable. Check 8020 before creating a bundle; 8009 only proves the Control Center API is alive.')
    expect(pullBundlePanel).toContain('Clean-to-commit / backup')
    expect(pullBundlePanel).toContain('Create is blocked until scope check is Ready and pull authority is fresh.')
    expect(pullBundlePanel).toContain('repo cleanliness, skipped entries, and exposure findings still need review')
    expect(pullBundlePanel).toContain('VPN required for live verification')
    expect(pullBundlePanel).toContain('Truth source:')
    expect(pullBundlePanel).toContain('Authority data as of:')
    expect(pullBundlePanel).toContain('Truth as of:')
    expect(pullBundlePanel).toContain('preflightContextKey')
    expect(pullBundlePanel).toContain('cachedPreflightStale')
    expect(pullBundlePanel).toContain('Cached Ready is stale. Run Check scope again.')
    expect(pullBundlePanel).toContain('Needs refresh')
  })

  it('shows backup-clean pull-bundle profile and compact review summaries', () => {
    expect(pullBundlePanel).toContain('Bundle profile: backup-clean')
    expect(pullBundlePanel).toContain('Backup readiness:')
    expect(pullBundlePanel).toContain('Backup readiness: review required')
    expect(pullBundlePanel).toContain('Unresolved exposures:')
    expect(pullBundlePanel).toContain('skipped review:')
    expect(pullBundlePanel).toContain('legacy proof')
    expect(pullBundlePanel).toContain('preflightReadyToCreate')
    expect(pullBundlePanel).toContain('!preflightReadyToCreate')
    expect(pullBundlePanel).toContain('bundle_profile')
    expect(pullBundlePanel).toContain('metadata_summaries')
    expect(pullBundlePanel).toContain('backup_readiness_status')
    expect(pullBundlePanel).toContain('unresolved_exposure_count')
    expect(pullBundlePanel).toContain('Skipped summary:')
    expect(pullBundlePanel).toContain('Showing first 12 exposure findings.')
    expect(pullBundlePanel).toContain('Exposure Review')
    expect(pullBundlePanel).toContain('false_positive')
    expect(pullBundlePanel).toContain('needs_action')
    expect(pullBundlePanel).toContain('accepted_risk')
    expect(types).toContain('PullBundleExposureReview')
    expect(types).toContain('ExposureReviewState')
    expect(types).toContain('PullBundleMetadataSummaries')
    expect(types).toContain('backup_clean')
    expect(types).toContain('review_required')
    expect(types).toContain('exposure_variable_summary')
  })

  it('keeps GitHub backup dry run report-only and attached to pull bundles', () => {
    expect(apiClient).toContain('listPullBundleGithubBackupDryRuns')
    expect(apiClient).toContain('createPullBundleGithubBackupDryRun')
    expect(apiClient).toContain('/services/${id}/github-backup-dry-runs')
    expect(pullBundlePanel).toContain('GitHub backup dry run')
    expect(pullBundlePanel).toContain('Run report')
    expect(pullBundlePanel).toContain('not push ready')
    expect(pullBundlePanel).toContain('No dry-run report yet. This report is diagnostic only and will not push, stage, commit, or create a bundle.')
    expect(pullBundlePanel).toContain('No push, stage, or commit performed.')
    expect(pullBundlePanel).not.toContain('GitHub Backup panel')
    expect(types).toContain('PullBundleGithubBackupDryRun')
    expect(types).toContain('push_performed')
    expect(types).toContain('commit_performed')
    expect(types).toContain('stage_performed')
  })
})
